//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkspaceCFG {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class MySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MySettings defaultInstance = ((MySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings())));
        
        public static MySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChosenApplication {
            get {
                return ((string)(this["ChosenApplication"]));
            }
            set {
                this["ChosenApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChosenApplicationPath {
            get {
                return ((string)(this["ChosenApplicationPath"]));
            }
            set {
                this["ChosenApplicationPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWorkspaceDirectory {
            get {
                return ((string)(this["LastWorkspaceDirectory"]));
            }
            set {
                this["LastWorkspaceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChosenWorkspace {
            get {
                return ((string)(this["ChosenWorkspace"]));
            }
            set {
                this["ChosenWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChosenWorkset {
            get {
                return ((string)(this["ChosenWorkset"]));
            }
            set {
                this["ChosenWorkset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WRK1_OP1 {
            get {
                return ((bool)(this["WRK1_OP1"]));
            }
            set {
                this["WRK1_OP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WRK1_OP2 {
            get {
                return ((bool)(this["WRK1_OP2"]));
            }
            set {
                this["WRK1_OP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WRK2_OP1 {
            get {
                return ((bool)(this["WRK2_OP1"]));
            }
            set {
                this["WRK2_OP1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WRK2_OP2 {
            get {
                return ((bool)(this["WRK2_OP2"]));
            }
            set {
                this["WRK2_OP2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WRK1_ChosenApplication {
            get {
                return ((string)(this["WRK1_ChosenApplication"]));
            }
            set {
                this["WRK1_ChosenApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("untitled")]
        public string WRK1_ChosenWorkspace {
            get {
                return ((string)(this["WRK1_ChosenWorkspace"]));
            }
            set {
                this["WRK1_ChosenWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("untitled")]
        public string WRK1_ChosenWorkset {
            get {
                return ((string)(this["WRK1_ChosenWorkset"]));
            }
            set {
                this["WRK1_ChosenWorkset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WRK2_ChosenApplication {
            get {
                return ((string)(this["WRK2_ChosenApplication"]));
            }
            set {
                this["WRK2_ChosenApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("untitled")]
        public string WRK2_ChosenWorkspace {
            get {
                return ((string)(this["WRK2_ChosenWorkspace"]));
            }
            set {
                this["WRK2_ChosenWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("untitled")]
        public string WRK2_ChosenWorkset {
            get {
                return ((string)(this["WRK2_ChosenWorkset"]));
            }
            set {
                this["WRK2_ChosenWorkset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WRK1_ChosenFile {
            get {
                return ((string)(this["WRK1_ChosenFile"]));
            }
            set {
                this["WRK1_ChosenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WRK2_ChosenFile {
            get {
                return ((string)(this["WRK2_ChosenFile"]));
            }
            set {
                this["WRK2_ChosenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point VE_Location {
            get {
                return ((global::System.Drawing.Point)(this["VE_Location"]));
            }
            set {
                this["VE_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowsDefaultLocation")]
        public global::System.Windows.Forms.FormStartPosition VE_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["VE_StartPos"]));
            }
            set {
                this["VE_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VE_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VE_WindowState"]));
            }
            set {
                this["VE_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1023, 881")]
        public global::System.Drawing.Size VE_Size {
            get {
                return ((global::System.Drawing.Size)(this["VE_Size"]));
            }
            set {
                this["VE_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point VC_Location {
            get {
                return ((global::System.Drawing.Point)(this["VC_Location"]));
            }
            set {
                this["VC_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowsDefaultLocation")]
        public global::System.Windows.Forms.FormStartPosition VC_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["VC_StartPos"]));
            }
            set {
                this["VC_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VC_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VC_WindowState"]));
            }
            set {
                this["VC_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("897, 660")]
        public global::System.Drawing.Size VC_Size {
            get {
                return ((global::System.Drawing.Size)(this["VC_Size"]));
            }
            set {
                this["VC_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("340")]
        public int VE_Split1_Dist {
            get {
                return ((int)(this["VE_Split1_Dist"]));
            }
            set {
                this["VE_Split1_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("406")]
        public int VC_Split1_Dist {
            get {
                return ((int)(this["VC_Split1_Dist"]));
            }
            set {
                this["VC_Split1_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("406")]
        public int VC_Split2_Dist {
            get {
                return ((int)(this["VC_Split2_Dist"]));
            }
            set {
                this["VC_Split2_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("356")]
        public int VC_Split3_Dist {
            get {
                return ((int)(this["VC_Split3_Dist"]));
            }
            set {
                this["VC_Split3_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point VR_Location {
            get {
                return ((global::System.Drawing.Point)(this["VR_Location"]));
            }
            set {
                this["VR_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition VR_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["VR_StartPos"]));
            }
            set {
                this["VR_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VR_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VR_WindowState"]));
            }
            set {
                this["VR_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("759, 763")]
        public global::System.Drawing.Size VR_Size {
            get {
                return ((global::System.Drawing.Size)(this["VR_Size"]));
            }
            set {
                this["VR_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185")]
        public int VR_Split2_Dist {
            get {
                return ((int)(this["VR_Split2_Dist"]));
            }
            set {
                this["VR_Split2_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("390")]
        public int VR_Split3_Dist {
            get {
                return ((int)(this["VR_Split3_Dist"]));
            }
            set {
                this["VR_Split3_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point ST_Location {
            get {
                return ((global::System.Drawing.Point)(this["ST_Location"]));
            }
            set {
                this["ST_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition ST_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["ST_StartPos"]));
            }
            set {
                this["ST_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point GC_Location {
            get {
                return ((global::System.Drawing.Point)(this["GC_Location"]));
            }
            set {
                this["GC_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition GC_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["GC_StartPos"]));
            }
            set {
                this["GC_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point EH_Location {
            get {
                return ((global::System.Drawing.Point)(this["EH_Location"]));
            }
            set {
                this["EH_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition EH_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["EH_StartPos"]));
            }
            set {
                this["EH_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("833, 668")]
        public global::System.Drawing.Size EH_Size {
            get {
                return ((global::System.Drawing.Size)(this["EH_Size"]));
            }
            set {
                this["EH_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState EH_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["EH_WindowState"]));
            }
            set {
                this["EH_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point FV_Location {
            get {
                return ((global::System.Drawing.Point)(this["FV_Location"]));
            }
            set {
                this["FV_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition FV_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["FV_StartPos"]));
            }
            set {
                this["FV_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("834, 659")]
        public global::System.Drawing.Size FV_Size {
            get {
                return ((global::System.Drawing.Size)(this["FV_Size"]));
            }
            set {
                this["FV_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FV_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FV_WindowState"]));
            }
            set {
                this["FV_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point FH_Location {
            get {
                return ((global::System.Drawing.Point)(this["FH_Location"]));
            }
            set {
                this["FH_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("891, 551")]
        public global::System.Drawing.Size FH_Size {
            get {
                return ((global::System.Drawing.Size)(this["FH_Size"]));
            }
            set {
                this["FH_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FH_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["FH_WindowState"]));
            }
            set {
                this["FH_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point MAIN_Location {
            get {
                return ((global::System.Drawing.Point)(this["MAIN_Location"]));
            }
            set {
                this["MAIN_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowsDefaultLocation")]
        public global::System.Windows.Forms.FormStartPosition Main_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["Main_StartPos"]));
            }
            set {
                this["Main_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point PS_Location {
            get {
                return ((global::System.Drawing.Point)(this["PS_Location"]));
            }
            set {
                this["PS_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterParent")]
        public global::System.Windows.Forms.FormStartPosition PS_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["PS_StartPos"]));
            }
            set {
                this["PS_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Shortcut_Args {
            get {
                return ((string)(this["Shortcut_Args"]));
            }
            set {
                this["Shortcut_Args"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string Shortcut_Out {
            get {
                return ((string)(this["Shortcut_Out"]));
            }
            set {
                this["Shortcut_Out"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public int FH_Split1_Dist {
            get {
                return ((int)(this["FH_Split1_Dist"]));
            }
            set {
                this["FH_Split1_Dist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition VL_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["VL_StartPos"]));
            }
            set {
                this["VL_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point VL_Location {
            get {
                return ((global::System.Drawing.Point)(this["VL_Location"]));
            }
            set {
                this["VL_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VL_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VL_WindowState"]));
            }
            set {
                this["VL_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("935, 729")]
        public global::System.Drawing.Size VL_Size {
            get {
                return ((global::System.Drawing.Size)(this["VL_Size"]));
            }
            set {
                this["VL_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point Loc_Location {
            get {
                return ((global::System.Drawing.Point)(this["Loc_Location"]));
            }
            set {
                this["Loc_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState Loc_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["Loc_WindowState"]));
            }
            set {
                this["Loc_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 295")]
        public global::System.Drawing.Size Loc_Size {
            get {
                return ((global::System.Drawing.Size)(this["Loc_Size"]));
            }
            set {
                this["Loc_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point SRCH_Location {
            get {
                return ((global::System.Drawing.Point)(this["SRCH_Location"]));
            }
            set {
                this["SRCH_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState SRCH_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["SRCH_WindowState"]));
            }
            set {
                this["SRCH_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("775, 425")]
        public global::System.Drawing.Size SRCH_Size {
            get {
                return ((global::System.Drawing.Size)(this["SRCH_Size"]));
            }
            set {
                this["SRCH_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public global::System.Windows.Forms.FormStartPosition VG_StartPos {
            get {
                return ((global::System.Windows.Forms.FormStartPosition)(this["VG_StartPos"]));
            }
            set {
                this["VG_StartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40")]
        public global::System.Drawing.Point VG_Location {
            get {
                return ((global::System.Drawing.Point)(this["VG_Location"]));
            }
            set {
                this["VG_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("653, 447")]
        public global::System.Drawing.Size VG_Size {
            get {
                return ((global::System.Drawing.Size)(this["VG_Size"]));
            }
            set {
                this["VG_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState VG_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["VG_WindowState"]));
            }
            set {
                this["VG_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chosen_OOB {
            get {
                return ((bool)(this["Chosen_OOB"]));
            }
            set {
                this["Chosen_OOB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Chosen_LOCAL {
            get {
                return ((bool)(this["Chosen_LOCAL"]));
            }
            set {
                this["Chosen_LOCAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VE_C1 {
            get {
                return ((bool)(this["VE_C1"]));
            }
            set {
                this["VE_C1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VE_C2 {
            get {
                return ((bool)(this["VE_C2"]));
            }
            set {
                this["VE_C2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VE_C3 {
            get {
                return ((bool)(this["VE_C3"]));
            }
            set {
                this["VE_C3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VE_C4 {
            get {
                return ((bool)(this["VE_C4"]));
            }
            set {
                this["VE_C4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VE_C5 {
            get {
                return ((bool)(this["VE_C5"]));
            }
            set {
                this["VE_C5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VE_C6 {
            get {
                return ((bool)(this["VE_C6"]));
            }
            set {
                this["VE_C6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GroupWindows {
            get {
                return ((bool)(this["GroupWindows"]));
            }
            set {
                this["GroupWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VE_MULTILINE {
            get {
                return ((bool)(this["VE_MULTILINE"]));
            }
            set {
                this["VE_MULTILINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResolveFilePaths {
            get {
                return ((bool)(this["ResolveFilePaths"]));
            }
            set {
                this["ResolveFilePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoloadLastWorkspace {
            get {
                return ((bool)(this["AutoloadLastWorkspace"]));
            }
            set {
                this["AutoloadLastWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoloadWorkspaceSelector {
            get {
                return ((bool)(this["AutoloadWorkspaceSelector"]));
            }
            set {
                this["AutoloadWorkspaceSelector"] = value;
            }
        }
    }
}
